---
language: node_js
node_js:
- "8"
- "10"

sudo: false
dist: trusty

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1

install: yarn install --no-lockfile --non-interactive
before_script: greenkeeper-lockfile-update
script: yarn test
after_script: greenkeeper-lockfile-upload
